config/routes.rb
TrainingRails::Application.routes.draw do
  get "sessions/new"

  get "session/new"

  get "users/new"
  
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users  

  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"

  namespace :admin do
   resources :articles, :menus, :users, :products, :categories, :countries, :comments
  end

  resources :products, :articles, :categories, :users, :countries, :sessions, :menus, :comments
  root :to => 'articles#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :article_id
  validates :content, :presence => { :message => "You must be filled 'content' "}
  belongs_to :user
  belongs_to :article
end

app/models/comments.rb
class Comments < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]
before_filter :find_comment, :only => [:edit, :update, :show, :destroy]

  def index
    @comments = Comment.find(:all)
  end

  def new
    @comment = Comment.new
  end

  def create
  	@comment = Comment.new(params[:comment])
  	respond_to do |format|
	   if @comment.save
	  	format.html { redirect_to(article_path(article), :notice => 'Comment was successfully created.') }
      format.js { @comments = Article.find(params[:comment][:article_id].to_i).comments }
	  end
	  end
    
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      flash[:notice] = 'Comment was successfully updated.'
      redirect_to(@comment)
    else
      flash[:error] = 'Comment was failed to update.'
      render :action => "edit"
    end
  end

  def show
      @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user_id == session[:user_id]
      #flash[:notice] = "Comment is deleted."
      @comment.destroy ? (flash[:error] = "Comment successfully deleted") :
                    (flash[:notice] = "Comment failed to delete")
      redirect_to comments_url
    else
      @comment.destroy ? (flash[:error] = "Comment successfully deleted") :
                    (flash[:notice] = "Comment failed to delete")
      redirect_to comments_url
    end
  end

  private
    def find_comment
      @comment = Comment.find_by_id(params[:id])
      if @comment.nil?
        flash[:notice] = "Cannot find the comment"
        redirect_to comments_url
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.js.erb
$("#comments").html(" <%= j( render :partial => 'admin/articles/comments',
                             :locals => {:comments => @comments} ) %>")
$("#comment_content").val("");

app/views/comments/edit.html.erb
<h1>Edit Comment Detail</h1>
<%= form_for @comment do |f| %>
<p>
  <label >Content</label> :
  <%= f.text_field :content %>
</p>
<p>
  <label >User ID</label> :
  <%= f.text_field :user_id %>
</p>
<p>
  <label >Article ID</label> :
  <%= f.text_field :article_id %>
</p>

<%= f.submit  "Save changes" %>
<% end %>

app/views/comments/index.html.erb
<h1>List of Comments</h1>

<table border="1">
  <thead>
    <tr>
      <th>Content</th>
      <th>Options</th>
    </tr>
  </thead>

  <% @comments.each do |comment| %>
    <tr>
      <td><%= link_to comment.content, comment %></td>
      <td>
        <%= link_to 'Edit', edit_comment_path(comment.id) %>
        <%= link_to 'Delete', comment_path(comment.id), :method => :delete, :data => { confirm: 'Are you sure?' }  %>
      </td>
    </tr>
  <% end -%>
</table>

<p><%= link_to 'New Comment', new_comment_path %></p>

app/views/comments/new.html.erb
<h1>Add New Comment</h1>
<%= form_for @comment do |f| %> 
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  Content : <%= f.text_field :content %>  <br />
  User ID : <%= f.text_field :user_id %>  <br />
  Article ID : <%= f.text_field :article_id %>  <br />
  <%=f.submit :create %>
<% end %>

app/views/comments/show.html.erb
<h1><%= @comment.content %></h1>
<p>
  <%= @comment.user_id %>
</p>

<a href="/comments/<%= @comment.id %>/edit">Edit</a>