config/routes.rb
TrainingRails::Application.routes.draw do
  get "sessions/new"

  get "session/new"

  get "users/new"
  
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users  

  get "log_in" => "sessions#new", :as => "log_in" 
  resources :sessions

  get "log_out" => "sessions#destroy", :as => "log_out"

  namespace :admin do
   resources :articles, :menus, :users, :products, :categories, :countries, :comments
  end

  resources :products, :articles, :categories, :users, :countries, :sessions, :menus, :comments
  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :descriptions, :rating, :user_id
  validates :title, :presence => { :message => "You must be filled 'title' "},
  					:uniqueness => true
  validates :descriptions, :presence => { :message => "You must be filled 'descriptions' "}
  belongs_to :user
  has_many :comments, :dependent => :destroy
  scope :rating, lambda {|time| where("rating < ?", time) }
  
  def self.show_one_hundred()
  	where("length(descriptions) > 100")
  end

end

app/models/articles.rb
class Articles < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
before_filter :require_admin_login, :only => [:new, :create, :edit, :update, :delete, :index]	

	def new
		#debugger
		@article = Article.new
	end


	def index
		@article = Article.all
		ap @article
	end


	def create
		@article = Article.new(params[:article])
      if @article.save
      		flash[:notice] = 'User was successfully created.'
      	    redirect_to :action => 'index'
      else
      		flash[:error] = 'User was failed to create.'
      		redirect_to :action => 'new'
      end
	end


	def edit
		@article = Article.find(params[:id])
	end


	def update
		@article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
      	 flash[:notice] = 'User was successfully updated.'
         redirect_to :action => 'index', :controller => 'admin/articles'
      else
      	 flash[:error] = 'User was failed to updated.'
         render :action => 'edit'
      end		
	end


	def show
		@comments = Comment.find_all_by_article_id(params[:id])
		@comment = Comment.new
		@article = Article.find(params[:id])
	end


	def destroy
		@article = Article.find(params[:id])
 		
 			@article.destroy ? (flash[:error] = "Article successfully deleted") : (flash[:notice] = "Article failed to delete")
 			redirect_to admin_articles_url
 	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_filter :require_login, :only => [:new, :create, :edit, :update, :delete, :index]	
	def new
		@article = Article.new
	end


	def index
		@articles = Article.all
	end


	def create
		@article = Article.new(params[:article])
      if @article.save
      		flash[:notice] = 'User was successfully created.'
      	    redirect_to :action => 'index'
      else
      		flash[:error] = 'User was failed to create.'
      		redirect_to :action => 'new'
      end
	end


	def edit
		@article = Article.find(params[:id])
		if @article.user_id == session[:user_id]
			@article = Article.find(params[:id])	
		else
			flash[:notice] = "You are not permitted."
 			redirect_to articles_url
		end	
	end


	def update
		@article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
      	 flash[:notice] = 'User was successfully updated.'
         redirect_to :action => 'index'
      else
      	 flash[:error] = 'User was failed to updated.'
         render :action => 'edit'
      end		
	end


	def show
		@comments = Comment.find_all_by_article_id(params[:id])
		@comment = Comment.new
		@article = Article.find(params[:id])
	end


	def destroy
		@article = Article.find(params[:id])
 		if @article.user_id == session[:user_id]
 			@article.destroy ? (flash[:error] = "Article successfully deleted") : (flash[:notice] = "Article failed to delete")
 			redirect_to articles_url
 		else
 			#redirect_to :action => 'index'
 			flash[:notice] = "Article failed to delete"
 			redirect_to articles_url
 		end
	end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>
    <ul>
    	<li> <%= comment.content %> </li>
    </ul>
  <% end %>

app/views/articles/create.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>App Name</title>
  <%= stylesheet_link_tag    "public" %>
  <%= javascript_include_tag "JQuery", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Create Articles</h1>
<%= yield %>

</body>
</html>

app/views/articles/edit.html.erb
<h1>Update Article</h1>
<%= form_for @article do |f| %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>

	<p><label for="article_title">Name</label>:
		<%= f.text_field :title %></p>
	<p><label for="article_rating">Rating</label>:
		<%= f.text_field :rating %></p>
	<p><label for="article_description">Description</label><br/>
		<%= f.text_area :descriptions %></p>
		<%= f.hidden_field :user_id, :value => current_user.id %></p>
		<%= f.submit :update%>
		<%= link_to 'Back', {:action => 'index'} %>
<% end %>

app/views/articles/index.html.erb
<%= yield %>
<h1>Index Article </h1>

<%# = @product %>
<table class="pretty" border="1">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Rating</th>
    <th>Action</th>
  </tr>
  <% for article in @articles %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.descriptions %></td>
    <td><%= article.rating %></td>
    <td>
        <b> <%= link_to 'Show', {:action => "show", :id => article.id} %></b> |
        <b> <%= link_to 'Edit', {:action => "edit", :id => article.id} %></b> |
        <b> <%= link_to 'Delete', {:action => "destroy", :id => article.id}, :method => :delete, :confirm => "Are you sure you want to delete this item?" %></b>
    </td>
  </tr>
  <% end %>
</table>

<p><%= link_to "Add New Article", {:controller => "articles", :action => "new"}, :class => "new-article" %></p>
<p><%= link_to "Back to Home", {:controller => "menus", :action => "index"}, :class => "new-article" %></p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for @article do |f| %>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>

	<p><label for="article_title">Name</label>:
		<%= f.text_field :title %></p>
	<p><label for="article_rating">Rating</label>:
		<%= f.text_field :rating %></p>
	<p><label for="article_description">Description</label><br/>
	    <%= f.hidden_field :user_id, :value => current_user.id %></p>
		<%= f.text_area :descriptions %></p>
		<%= f.submit :create%>
		<%= link_to 'Back', {:action => 'index'} %>
<% end %>

app/views/articles/show.html.erb
<!--This section is to show all comments that owned by the article  -->
<div id="comments">
<h4>Comment</h4>
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div>


<% unless(current_user.nil?)%>
	<h4>Add New Comment</h4>
   <%= form_for @comment, :url => comments_path, :remote => true do |f| %>
      <%= f.text_area :content, :size => '60px' %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= submit_tag "comment" %>
  <% end -%>
<% end %>

<h1><%= @article.title %></h1>
<p><strong>Rating: </strong> <%= @article.rating %><br />
<p> <%= @article.descriptions %> </p><br />

<hr />
<%= link_to 'Back', {:action => 'index'} %>